name: Test
on: push
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@0df5d9c641efdff149993c321fc27c11c5df8623 # v1.1.3
        with:
          deno-version: v1.x
      - name: Download wabt
        run: |
          curl -L https://github.com/WebAssembly/wabt/releases/download/1.0.30/wabt-1.0.30-ubuntu.tar.gz | tar -xz -C ~
          echo "$HOME/wabt-1.0.30/bin" >> $GITHUB_PATH
      - run: deno task star
      - run: deno task build --check
      - run: deno task test
